version: '3.8'

x-pg: &pg-template
  image: postgres:15
  environment:
    POSTGRES_USER: ${POSTGRES_USER:-postgres}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    POSTGRES_DB: database_name
  ports:
    - 5432:5432
  restart: unless-stopped

services:
  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - 6379:6379
  redisinsight:
    image: redislabs/redisinsight:latest
    depends_on:
      - redis
    ports:
      - 8001:8001
    environment:
      - REDIS_PASSWORD=changeme
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    depends_on:
      - redis
    # environment:
    #   - GF_SECURITY_ADMIN_PASSWORD=changeme

  pg-bank:
    <<: *pg-template
    env_file: ./.env
    container_name: ${DATABASE_NAME}
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      PGDATA: /data/postgres
    volumes:
      - db-bank:/data/postgres

  bank-api:
    restart: on-failure:2
    build:
      context: .
      dockerfile: Dockerfile
    image: bank-api
    container_name: bank-api
    command: sh -c 'echo "waiting for pg-bank:5432..." && wait-for -t 3 pg-bank:5432 -- /app/main || echo "Failed to connect to pg-banks:5432"'
    depends_on:
      - pg-bank
    environment: # override .env values
      - DATABASE_HOST=pg-bank
      - GIN_MODE=debug
      - ACCESS_TOKEN_DURATION=5m
    env_file: .env
    volumes:
      - .env:/app/.env
    ports:
      - 8080:8080


volumes:
    db-bank: