version: '3.8'

x-pg: &pg-template
  image: postgres:15
  environment:
    POSTGRES_USER: ${POSTGRES_USER:-postgres}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    POSTGRES_DB: database_name
  ports:
    - 5432:5432
  restart: unless-stopped

services:
  pg-bank:
    <<: *pg-template
    env_file: ./.env
    container_name: ${DATABASE_NAME}
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      PGDATA: /data/postgres
    volumes:
      - db-bank:/data/postgres

volumes:
    db-bank: