version: '3'
dotenv: ['.env']
tasks:
  init:
    - echo $AWS_SECRET_ACCESS_KEY
    - bash ./hack/aws.sh
  cluster:
    - eksctl create cluster -f ./clusters/polygon.yaml
  alb: # https://github.com/kubernetes-sigs/aws-load-balancer-controller/tree/1abc9bb0fffdcef0967710a4903e1bd55e1359d1/helm/aws-load-balancer-controller
    - eksctl utils associate-iam-oidc-provider --config-file=./clusters/polygon.yaml
    - eksctl create iamserviceaccount --config-file=./clusters/polygon.yaml --approve
    - helm repo add eks https://aws.github.io/eks-charts
    - helm repo update eks
    - helm upgrade -n kube-system --install aws-load-balancer-controller eks/aws-load-balancer-controller --values ./helm/kube-system/aws-load-balancer-controller.yaml

  argo:
    - kubectl create namespace argocd
    - kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  argo-login:
    - kubectl port-forward svc/argocd-server -n argocd 8080:443 & echo "http://localhost:8080"
    - argocd login localhost:8080 --username admin --password $(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d; echo) --insecure

  argo-pass:
    - echo "\/password\/" && kubectl get secret -n argocd argocd-initial-admin-secret -o jsonpath='{.data.*}' | base64 -d | cut -c 1-
    # - argocd login localhost:8080 --username admin
    # - kubectl get secret -n argocd argocd-initial-admin-secret -o jsonpath='{.data.*}' | base64 -d argocd login localhost:8080 --username admin --password





  2137:
    - kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/main/docs/examples/2048/2048_full.yaml

  apps:
    - |
      argocd app create apps \
      --dest-namespace argocd \
      --dest-server https://kubernetes.default.svc \
      --repo https://github.com/argoproj/argocd-example-apps.git \
      --path apps 